server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nevermore.top:3306/mybatis
    username: xia
    password: root123456
mybatis:
  mapper-locations: classpath:/mappers/*.xml
